# ------------------------------------------------------------------------------ #
# 
# Code to clean imputed dataset 
# 
#
# Author: 
#
# Cynthia M. Kroeger, University of Sydney (cynthia.kroeger@sydney.edu.au)
#
# 
# ------------------------------------------------------------------------------ #
# Read in data  
# ------------------------------------------------------------------------------ #
file_name <- "imp_data_l_all_14_dec_2018.csv"
dat <- read.csv(file_name)
head(dat)
summary(dat)


# ------------------------------------------------------------------------------ #
# Create columns for week 1 of outcome variables to use as covariates 
# ------------------------------------------------------------------------------ #
library(dplyr)


# subset each imputation and add baseline columns for outcome measures 
imp_1 <- subset(dat, .imp == 1)
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_1 <- imp_1 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_2 <- subset(dat, .imp == 2)
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_2 <- imp_2 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_3 <- subset(dat, .imp == 3)
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_3 <- imp_3 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_4 <- subset(dat, .imp == 4)
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_4 <- imp_4 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_5 <- subset(dat, .imp == 5)
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_5 <- imp_5 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_6 <- subset(dat, .imp == 6)
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_6 <- imp_6 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_7 <- subset(dat, .imp == 7)
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_7 <- imp_7 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_8 <- subset(dat, .imp == 8)
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_8 <- imp_8 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_9 <- subset(dat, .imp == 9)
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_9 <- imp_9 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_10 <- subset(dat, .imp == 10)
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_10 <- imp_10 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_11 <- subset(dat, .imp == 11)
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_11 <- imp_11 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_12 <- subset(dat, .imp == 12)
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_12 <- imp_12 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_13 <- subset(dat, .imp == 13)
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_13 <- imp_13 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_14 <- subset(dat, .imp == 14)
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_14 <- imp_14 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_15 <- subset(dat, .imp == 15)
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_15 <- imp_15 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_16 <- subset(dat, .imp == 16)
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_16 <- imp_16 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_17 <- subset(dat, .imp == 17)
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_17 <- imp_17 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_18 <- subset(dat, .imp == 18)
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_18 <- imp_18 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_19 <- subset(dat, .imp == 19)
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_19 <- imp_19 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_20 <- subset(dat, .imp == 20)
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_20 <- imp_20 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_21 <- subset(dat, .imp == 21)
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_21 <- imp_21 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_22 <- subset(dat, .imp == 22)
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_22 <- imp_22 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_23 <- subset(dat, .imp == 23)
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_23 <- imp_23 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_24 <- subset(dat, .imp == 24)
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_24 <- imp_24 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_25 <- subset(dat, .imp == 25)
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_25 <- imp_25 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_26 <- subset(dat, .imp == 26)
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_26 <- imp_26 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_27 <- subset(dat, .imp == 27)
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_27 <- imp_27 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_28 <- subset(dat, .imp == 28)
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_28 <- imp_28 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_29 <- subset(dat, .imp == 29)
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_29 <- imp_29 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_30 <- subset(dat, .imp == 30)
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_30 <- imp_30 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_31 <- subset(dat, .imp == 31)
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_31 <- imp_31 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_32 <- subset(dat, .imp == 32)
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_32 <- imp_32 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_33 <- subset(dat, .imp == 33)
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_33 <- imp_33 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_34 <- subset(dat, .imp == 34)
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_34 <- imp_34 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_35 <- subset(dat, .imp == 35)
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_35 <- imp_35 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_36 <- subset(dat, .imp == 36)
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_36 <- imp_36 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_37 <- subset(dat, .imp == 37)
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_37 <- imp_37 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_38 <- subset(dat, .imp == 38)
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_38 <- imp_38 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_39 <- subset(dat, .imp == 39)
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_39 <- imp_39 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_40 <- subset(dat, .imp == 40)
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_40 <- imp_40 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_41 <- subset(dat, .imp == 41)
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_41 <- imp_41 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_42 <- subset(dat, .imp == 42)
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_42 <- imp_42 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_43 <- subset(dat, .imp == 43)
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_43 <- imp_43 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_44 <- subset(dat, .imp == 44)
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_44 <- imp_44 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_45 <- subset(dat, .imp == 45)
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_45 <- imp_45 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_46 <- subset(dat, .imp == 46)
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_46 <- imp_46 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_47 <- subset(dat, .imp == 47)
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_47 <- imp_47 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_48 <- subset(dat, .imp == 48)
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_48 <- imp_48 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_49 <- subset(dat, .imp == 49)
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_49 <- imp_49 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_50 <- subset(dat, .imp == 50)
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_50 <- imp_50 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_51 <- subset(dat, .imp == 51)
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_51 <- imp_51 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


imp_52 <- subset(dat, .imp == 52)
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(tfeq_rest_1 = tfeq_rest[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(tfeq_uncon_1 = tfeq_uncon[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(tfeq_emo_1 = tfeq_emo[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(vas_hung_1 = vas_hung[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(vas_satis_1 = vas_satis[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(vas_ful_1 = vas_ful[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(se_rel_1 = se_rel[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(se_cal_1 = se_cal[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(se_salt_1 = se_salt[week == 1])
imp_52 <- imp_52 %>% group_by(.id) %>% mutate(se_fat_1 = se_fat[week == 1])


# merge 52 datasets
imp_data_52 <- rbind(imp_1, imp_2, imp_3, imp_4, imp_5, imp_6, imp_7, imp_8, imp_9, 
                     imp_10, imp_11, imp_12, imp_13, imp_14, imp_15, imp_16, imp_17, 
                     imp_18, imp_19, imp_20, imp_21, imp_22, imp_23, imp_24, imp_25, 
                     imp_26, imp_27, imp_28, imp_29, imp_30, imp_31, imp_32, imp_33, 
                     imp_34, imp_35, imp_36, imp_37, imp_38, imp_39, imp_40, imp_41, 
                     imp_42, imp_43, imp_44, imp_45, imp_46, imp_47, imp_48, imp_49, 
                     imp_50, imp_51, imp_52)


# write .csv
write.csv(imp_data_52, 
          file = "imp_data_52.csv")
